name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
  - type: textarea
    attributes:
      label: Description
      description: What is the problem you are trying to solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Any other approaches?
